{{- if not .Values.api.existingSecret.name }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bright.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "bright.labels" . | nindent 4 }}
type: Opaque
data:
  token: {{ .Values.api.token | b64enc | quote }}
{{- end }}
